theme: minima

minima:
  social_links:
    github:  
     - username: CodeDoctorDE
       instance: github.com/CodeDoctorDE
     - username: louis-e
       instance: github.com/louis-e
     - username: dominikdev-m
       instance: github.com/dominikdev-m
     - username: McDochder
       instance: 49-game.com
  header_pages:
  - README.md
  - about.md